version: '3.7'

services:
  client:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/app:delegated
      - /opt/app/node_modules
    ports:
      - 8000:8000
      - 9229:9229
