version: '3.7'

services:
  client:
    build:
      dockerfile: Dockerfile
      context: .
      target: prod
    ports:
      - 8000:8000
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    links:
      - client
