name: run test on pull request

env:
  IMAGE_NAME: docker-nginx-nextjs

on:
  pull_request:
    branches: master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build docker image for testing
      env:
        DOCKER_BUILDKIT: 1
      run: docker build --target test -t=$IMAGE_NAME .
        
    - name: Run docker image
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        docker run $IMAGE_NAME -v "$PWD/coverage:/opt/app/coverage"
        bash <(curl -s https://codecov.io/bash)
